name: Deploy to CPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      # - name: 🧹 Remove Unwanted Files
      #   run: |
      #     rm -rf README.md
      #     rm -rf composer.json

      # - name: 🚚 Deploy Code via FTP
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ftp.starplus.co.id
      #     username: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PASS }}
      #     server-dir: /
      #     timeout: 2400000 # 40 menit

      # - name: SSH ke Server dan Jalankan Composer & PNPM
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       cd /path/to/your/project/
      #       composer install --no-dev --prefer-dist
      #       pnpm install --frozen-lockfile
  

      # utk sementara script composer install dimatikan. folder vendor di push secara manual
      # - name: 🔄 Trigger Composer Install on Server
      #   run: curl -s "https://harmoni-hub.com/run_composer.php?token=${{ secrets.RUN_TOKEN }}"